//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18046
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HappanedHere.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HappanedHere.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to all articles.
        /// </summary>
        public static string AllPivotItemTitle {
            get {
                return ResourceManager.GetString("AllPivotItemTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays articles from all the other categories.
        /// </summary>
        public static string AllTileDescription {
            get {
                return ResourceManager.GetString("AllTileDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string AllTileTitle {
            get {
                return ResourceManager.GetString("AllTileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An augmented reallity-based article reader for Windows Phone 7 and 8. Searches for news, historycal events, and more, happened near your current location, and shows them on the camera&apos;s picture live..
        /// </summary>
        public static string AppDescription {
            get {
                return ResourceManager.GetString("AppDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Happened Here.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact the developer: .
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Articles You saved for future reading.
        /// </summary>
        public static string EarlierTileDesciption {
            get {
                return ResourceManager.GetString("EarlierTileDesciption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earlier.
        /// </summary>
        public static string EarlierTileTitle {
            get {
                return ResourceManager.GetString("EarlierTileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to history.
        /// </summary>
        public static string HistoryPivotItemTitle {
            get {
                return ResourceManager.GetString("HistoryPivotItemTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History, where it happened.
        /// </summary>
        public static string HistoryTileDescription {
            get {
                return ResourceManager.GetString("HistoryTileDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string HistoryTileTitle {
            get {
                return ResourceManager.GetString("HistoryTileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HappenedHere needs your current location, to show the nearby articles. Please allow the program to use your current location..
        /// </summary>
        public static string LetFindLocationDescription {
            get {
                return ResourceManager.GetString("LetFindLocationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let HappenedHere use of your current position?.
        /// </summary>
        public static string LetFindLocationTitle {
            get {
                return ResourceManager.GetString("LetFindLocationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to news.
        /// </summary>
        public static string NewsPivotItemTitle {
            get {
                return ResourceManager.GetString("NewsPivotItemTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent news, where they happened.
        /// </summary>
        public static string NewsTileDesciption {
            get {
                return ResourceManager.GetString("NewsTileDesciption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        public static string NewsTileTitle {
            get {
                return ResourceManager.GetString("NewsTileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s lonely here. Save some articles you want to read later..
        /// </summary>
        public static string NoSavedArticles {
            get {
                return ResourceManager.GetString("NoSavedArticles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string Off {
            get {
                return ResourceManager.GetString("Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string On {
            get {
                return ResourceManager.GetString("On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pin to start.
        /// </summary>
        public static string PinToStart {
            get {
                return ResourceManager.GetString("PinToStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate+review.
        /// </summary>
        public static string Rate {
            get {
                return ResourceManager.GetString("Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to refresh articles.
        /// </summary>
        public static string RefreshArticles {
            get {
                return ResourceManager.GetString("RefreshArticles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save article.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to send via email.
        /// </summary>
        public static string SendEmail {
            get {
                return ResourceManager.GetString("SendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi! I think you would be interested in this article I read: .
        /// </summary>
        public static string ShareViaEmailBody {
            get {
                return ResourceManager.GetString("ShareViaEmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I want to share an article with you from HappenedHere Windows Phone App!.
        /// </summary>
        public static string ShareViaEmailSubject {
            get {
                return ResourceManager.GetString("ShareViaEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Map.
        /// </summary>
        public static string ShowMap {
            get {
                return ResourceManager.GetString("ShowMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sports.
        /// </summary>
        public static string SportsPivotItemTitle {
            get {
                return ResourceManager.GetString("SportsPivotItemTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nearby news from the world of sports.
        /// </summary>
        public static string SportsTileDesciption {
            get {
                return ResourceManager.GetString("SportsTileDesciption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sports.
        /// </summary>
        public static string SportsTileTitle {
            get {
                return ResourceManager.GetString("SportsTileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HAPPENED HERE.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle heading.
        /// </summary>
        public static string ToggleHeading {
            get {
                return ResourceManager.GetString("ToggleHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Location.
        /// </summary>
        public static string UseLocation {
            get {
                return ResourceManager.GetString("UseLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version: .
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to view in explorer.
        /// </summary>
        public static string ViewInExplorer {
            get {
                return ResourceManager.GetString("ViewInExplorer", resourceCulture);
            }
        }
    }
}
